<?php
# MetInfo Enterprise Content Management System 
# Copyright (C) MetInfo Co.,Ltd (http://www.metinfo.cn). All rights reserved.

defined('IN_MET') or exit('No permission');

define ('TEM_INSTALL_VER', '1.000');

class install {
	function dosql(){
		global $_M;		
		
$sql = array (
  0 => 'pos =\'1\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'大图轮播设置\',tips=\'\'',
  1 => 'pos =\'2\',no_order=\'1\',type=\'2\',style=\'3\',selectd=\'$M$隐藏$T$0$M$显示$T$1\',name =\'bannersub_modular_hide\',value=\'\',defaultvalue=\'\',valueinfo =\'隐藏头部大图\',tips=\'隐藏指定模块列表页的头部大图，请填写模块名称（简介模块请在详情页设置），多个用竖线（|）隔开，如：下载模块|招聘模块\'',
  2 => 'pos =\'3\',no_order=\'1\',type=\'2\',style=\'3\',selectd=\'$M$隐藏$T$0$M$显示$T$1\',name =\'bannersubdet_modular_hide\',value=\'文章模块|图片模块|产品模块\',defaultvalue=\'文章模块|图片模块|产品模块\',valueinfo =\'隐藏头部大图\',tips=\'隐藏指定模块详情页的头部大图，请填写模块名称，多个用竖线（|）隔开，如：下载模块|招聘模块\'',
  3 => 'pos =\'0\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'风格设置\',tips=\'\'',
  4 => 'pos =\'3\',no_order=\'2\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\'',
  5 => 'pos =\'1\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$宽高自适应$T$0$M$固定高度$T$1\',name =\'bannertype\',value=\'0\',defaultvalue=\'0\',valueinfo =\'展示模式\',tips=\'宽高自适应：图片100%浏览器宽度，高度按比例缩放，展示完整图片；固定高度：不同设备设置不同高度（三个高度都要设置，电脑端高度在“原banner设置”里，推荐设置与图片原始高度保持一致，最小值300），宽度按比例缩放，显示图片中间内容\'',
  6 => 'pos =\'2\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$宽高自适应$T$0$M$固定高度$T$1\',name =\'bannersubtype\',value=\'0\',defaultvalue=\'0\',valueinfo =\'展示模式\',tips=\'请上传宽度为1920像素高度不小于150像素的图片，所有的轮播图片高度要一样。宽高自适应：图片100%浏览器宽度，高度按比例缩放，展示完整图片；固定高度：不同设备设置不同高度（三个高度都要设置，电脑端高度在“原banner设置”里，推荐设置与图片原始高度保持一致，最小值150），宽度按比例缩放，显示图片中间内容\'',
  7 => 'pos =\'0\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'默认风格$T$0$M$自定义风格$T$1$M$\',name =\'yourcolors_ok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'颜色选择\',tips=\'\'',
  8 => 'pos =\'3\',no_order=\'3\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'news_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\'',
  9 => 'pos =\'1\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'banner_height_sm\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度（平板电脑竖屏）\',tips=\'首页大图，最小值150，固定高度模式下设置\'',
  10 => 'pos =\'2\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'bannersub_height_sm\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度（平板电脑竖屏）\',tips=\'内页大图，最小值100，固定高度模式下设置\'',
  11 => 'pos =\'0\',no_order=\'3\',type=\'9\',style=\'3\',selectd=\'\',name =\'main_colors\',value=\'\',defaultvalue=\'\',valueinfo =\'主色调\',tips=\'\'',
  12 => 'pos =\'3\',no_order=\'4\',type=\'6\',style=\'3\',selectd=\'\',name =\'news_bar_list_id\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏文章列表调用栏目\',tips=\'默认调用当前一级栏目的内容\'',
  13 => 'pos =\'1\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'banner_height_xs\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度（手机）\',tips=\'首页大图，最小值150，固定高度模式下设置\'',
  14 => 'pos =\'2\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'bannersub_height_xs\',value=\'\',defaultvalue=\'\',valueinfo =\'图片高度（手机）\',tips=\'内页大图，最小值100，固定高度模式下设置\'',
  15 => 'pos =\'0\',no_order=\'4\',type=\'9\',style=\'3\',selectd=\'\',name =\'second_colors\',value=\'\',defaultvalue=\'\',valueinfo =\'辅色调\',tips=\'\'',
  16 => 'pos =\'3\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\'',
  17 => 'pos =\'1\',no_order=\'5\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'大图轮播第一屏\',tips=\'\'',
  18 => 'pos =\'2\',no_order=\'5\',type=\'9\',style=\'3\',selectd=\'\',name =\'bannersub_color\',value=\'#fff\',defaultvalue=\'#fff\',valueinfo =\'文字颜色\',tips=\'自定义模式下设置\'',
  19 => 'pos =\'0\',no_order=\'5\',type=\'9\',style=\'3\',selectd=\'\',name =\'font_colors\',value=\'\',defaultvalue=\'\',valueinfo =\'字体颜色\',tips=\'\'',
  20 => 'pos =\'0\',no_order=\'6\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部设置\',tips=\'\'',
  21 => 'pos =\'1\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'banner1_ok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'是否显示\',tips=\'\'',
  22 => 'pos =\'2\',no_order=\'6\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'头部背景\',tips=\'\'',
  23 => 'pos =\'3\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$全部文章$T$$M$推荐文章$T$com\',name =\'news_bar_list_type\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏列表文章类型\',tips=\'文章调用类型，【推荐文章】可以在添加或管理文章时设置。\'',
  24 => 'pos =\'0\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'navmarginleft\',value=\'0\',defaultvalue=\'0\',valueinfo =\'导航间距\',tips=\'仅支持5的倍数（0/5/10/15/20...最大50）<br/>不同网站的导航数量不同，根据需求适当调整间距，让网站更协调。\'',
  25 => 'pos =\'1\',no_order=\'7\',type=\'7\',style=\'3\',selectd=\'\',name =\'banner1_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片\',tips=\'请上传宽度为1920像素高度不小于300像素的图片，所有的轮播图片高度要一样。\'',
  26 => 'pos =\'2\',no_order=\'7\',type=\'9\',style=\'3\',selectd=\'\',name =\'page_top_bgcolor\',value=\'\',defaultvalue=\'\',valueinfo =\'背景颜色\',tips=\'如果需要设置图片，可以在内页大图轮播设置里面设置\'',
  27 => 'pos =\'3\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表文章数量\',tips=\'\'',
  28 => 'pos =\'0\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'navbarok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'导航下拉菜单\',tips=\'\'',
  29 => 'pos =\'2\',no_order=\'8\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\'',
  30 => 'pos =\'3\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_allcolumn\',value=\'所有文章\',defaultvalue=\'所有文章\',valueinfo =\'侧栏栏目区块标题\',tips=\'\'',
  31 => 'pos =\'1\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'banner1_link\',value=\'\',defaultvalue=\'\',valueinfo =\'图片链接\',tips=\'请输入完整的网址\'',
  32 => 'pos =\'0\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'navbarprohibit\',value=\'\',defaultvalue=\'\',valueinfo =\'禁用下拉名单\',tips=\'禁止指定栏目显示下拉菜单，请填写栏目名称，多个用竖线（|）隔开\'',
  33 => 'pos =\'2\',no_order=\'9\',type=\'4\',style=\'3\',selectd=\'$M$极简$T$1$M$图文$T$2$M$橱窗$T$3\',name =\'news_listtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'列表展示\',tips=\'橱窗模式下新闻头条无效\'',
  34 => 'pos =\'3\',no_order=\'9\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块\',tips=\'\'',
  35 => 'pos =\'1\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'banner1_title\',value=\'\',defaultvalue=\'\',valueinfo =\'标题\',tips=\'第一行文字，若不填则不显示\'',
  36 => 'pos =\'0\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$点击展开$T$0$M$鼠标经过$T$1\',name =\'navhoverok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'下拉方式\',tips=\'\'',
  37 => 'pos =\'2\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_headlines\',value=\'0\',defaultvalue=\'0\',valueinfo =\'新闻头条\',tips=\'头条将采用大图轮播的方式展现\'',
  38 => 'pos =\'3\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$标准$T$1$M$时尚$T$2\',name =\'product_pagetype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示方式\',tips=\'\'',
  39 => 'pos =\'1\',no_order=\'10\',type=\'9\',style=\'3\',selectd=\'\',name =\'banner1_titlecolor\',value=\'\',defaultvalue=\'\',valueinfo =\'标题文字颜色\',tips=\'\'',
  40 => 'pos =\'0\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'$M$带指向标$T$1$M$无$T$0\',name =\'navbulletok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'下拉展示\',tips=\'无指向标时会有动画效果\'',
  41 => 'pos =\'2\',no_order=\'11\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_headlines_num\',value=\'3\',defaultvalue=\'3\',valueinfo =\'头条数量\',tips=\'数量必须小于文章列表页每页显示条数\'',
  42 => 'pos =\'1\',no_order=\'11\',type=\'3\',style=\'3\',selectd=\'\',name =\'banner1_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述\',tips=\'第二行文字，如果要换行，请用HTML换行标记，若不填则不显示\'',
  43 => 'pos =\'3\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'pro_des_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'描述文字开关\',tips=\'\'',
  44 => 'pos =\'3\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'specpara\',value=\'规格参数\',defaultvalue=\'规格参数\',valueinfo =\'选项卡文字\',tips=\'时尚模式下设置\'',
  45 => 'pos =\'1\',no_order=\'12\',type=\'9\',style=\'3\',selectd=\'\',name =\'banner1_desccolor\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字颜色\',tips=\'\'',
  46 => 'pos =\'2\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_headlines_x\',value=\'900\',defaultvalue=\'900\',valueinfo =\'头条图片宽度\',tips=\'建议尺寸：900\'',
  47 => 'pos =\'0\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部信息\',tips=\'\'',
  48 => 'pos =\'3\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'shop_modal_title\',value=\'商品选项\',defaultvalue=\'商品选项\',valueinfo =\'弹框标题\',tips=\'启用商城模块后时尚模式下点击购买按钮弹框标题\'',
  49 => 'pos =\'1\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'$M$左$T$1$M$右$T$2$M$上$T$3$M$下$T$4$M$居中$T$5\',name =\'banner1_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'文字区域位置\',tips=\'\'',
  50 => 'pos =\'2\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_headlines_y\',value=\'300\',defaultvalue=\'300\',valueinfo =\'头条图片高度\',tips=\'建议尺寸：300\'',
  51 => 'pos =\'3\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_recommend\',value=\'热门推荐\',defaultvalue=\'热门推荐\',valueinfo =\'侧栏列表区块标题\',tips=\'\'',
  52 => 'pos =\'1\',no_order=\'14\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'大图轮播第二屏\',tips=\'\'',
  53 => 'pos =\'2\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_ccimg_x\',value=\'900\',defaultvalue=\'900\',valueinfo =\'橱窗模式图片宽度\',tips=\'建议尺寸：900\'',
  54 => 'pos =\'0\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'top_tell\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部文字\',tips=\'\'',
  55 => 'pos =\'0\',no_order=\'15\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'底部设置\',tips=\'\'',
  56 => 'pos =\'1\',no_order=\'15\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'banner2_ok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'是否显示\',tips=\'\'',
  57 => 'pos =\'3\',no_order=\'15\',type=\'4\',style=\'3\',selectd=\'$M$全部产品$T$$M$推荐产品$T$com\',name =\'product_hot_type\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏列表产品类型\',tips=\'产品调用类型，【推荐产品】可以在添加或管理文章时设置。\'',
  58 => 'pos =\'2\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_ccimg_y\',value=\'300\',defaultvalue=\'300\',valueinfo =\'橱窗模式图片高度\',tips=\'建议尺寸：300\'',
  59 => 'pos =\'0\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_navok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'底部导航区域\',tips=\'底部导航右侧为联系信息，左侧的二级导航最多显示四列。\'',
  60 => 'pos =\'1\',no_order=\'16\',type=\'7\',style=\'3\',selectd=\'\',name =\'banner2_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片\',tips=\'请上传宽度为1920像素高度不小于300像素的图片，所有的轮播图片高度要一样。\'',
  61 => 'pos =\'3\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_hot_num\',value=\'6\',defaultvalue=\'6\',valueinfo =\'侧栏列表产品数量\',tips=\'\'',
  62 => 'pos =\'2\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_des_max\',value=\'130\',defaultvalue=\'130\',valueinfo =\'描述文字字数\',tips=\'描述文字最多显示字数（最大设置值200）\'',
  63 => 'pos =\'0\',no_order=\'17\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_linksok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'首页友情链接\',tips=\'后台只能统一设置一种链接类型，文字链接或logo链接\'',
  64 => 'pos =\'2\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_moretxt\',value=\'更多文章\',defaultvalue=\'更多文章\',valueinfo =\'分页按钮文字\',tips=\'手机端采用无刷新加载\'',
  65 => 'pos =\'1\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'banner2_link\',value=\'\',defaultvalue=\'\',valueinfo =\'图片链接\',tips=\'请输入完整的网址\'',
  66 => 'pos =\'3\',no_order=\'17\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\'',
  67 => 'pos =\'0\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_links_title\',value=\'友情链接 :\',defaultvalue=\'友情链接 :\',valueinfo =\'友情链接标题\',tips=\'后台只能统一设置一种链接类型，文字链接或logo链接\'',
  68 => 'pos =\'2\',no_order=\'18\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块\',tips=\'\'',
  69 => 'pos =\'1\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'banner2_title\',value=\'\',defaultvalue=\'\',valueinfo =\'标题\',tips=\'第一行文字，若不填则不显示\'',
  70 => 'pos =\'3\',no_order=\'18\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'img_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\'',
  71 => 'pos =\'0\',no_order=\'19\',type=\'4\',style=\'3\',selectd=\'$M$头部$T$0$M$底部$T$1\',name =\'langlist_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'语言栏位置\',tips=\'\'',
  72 => 'pos =\'2\',no_order=\'19\',type=\'4\',style=\'3\',selectd=\'$M$标准$T$1$M$纯图$T$2$M$橱窗$T$3\',name =\'product_listtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'列表展示\',tips=\'\'',
  73 => 'pos =\'1\',no_order=\'19\',type=\'9\',style=\'3\',selectd=\'\',name =\'banner2_titlecolor\',value=\'\',defaultvalue=\'\',valueinfo =\'标题文字颜色\',tips=\'\'',
  74 => 'pos =\'3\',no_order=\'19\',type=\'6\',style=\'3\',selectd=\'\',name =\'img_bar_list_id\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏文章列表调用栏目\',tips=\'默认调用当前一级栏目的内容\'',
  75 => 'pos =\'0\',no_order=\'20\',type=\'4\',style=\'3\',selectd=\'$M$模态框（弹窗）$T$2$M$下拉菜单$T$1\',name =\'langlist_type\',value=\'2\',defaultvalue=\'2\',valueinfo =\'语言切换方式\',tips=\'\'',
  76 => 'pos =\'1\',no_order=\'20\',type=\'3\',style=\'3\',selectd=\'\',name =\'banner2_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述\',tips=\'第二行文字，如果要换行，请用HTML换行标记，若不填则不显示\'',
  77 => 'pos =\'3\',no_order=\'20\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\'',
  78 => 'pos =\'2\',no_order=\'20\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_listlook\',value=\'查看详情\',defaultvalue=\'查看详情\',valueinfo =\'查看按钮文字\',tips=\'橱窗模式按钮文字\'',
  79 => 'pos =\'0\',no_order=\'21\',type=\'4\',style=\'3\',selectd=\'显示$T$1$M$$M$隐藏$T$0\',name =\'langlist_icon_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'语言栏国旗开关\',tips=\'\'',
  80 => 'pos =\'2\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_moretxt\',value=\'更多产品\',defaultvalue=\'更多产品\',valueinfo =\'分页按钮文字\',tips=\'手机端采用无刷新加载\'',
  81 => 'pos =\'1\',no_order=\'21\',type=\'9\',style=\'3\',selectd=\'\',name =\'banner2_desccolor\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字颜色\',tips=\'\'',
  82 => 'pos =\'3\',no_order=\'21\',type=\'4\',style=\'3\',selectd=\'$M$全部文章$T$$M$推荐文章$T$com\',name =\'img_bar_list_type\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏列表文章类型\',tips=\'文章调用类型，【推荐文章】可以在添加或管理文章时设置。\'',
  83 => 'pos =\'0\',no_order=\'22\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'底部联系信息\',tips=\'\'',
  84 => 'pos =\'2\',no_order=\'22\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'product_search\',value=\'1\',defaultvalue=\'1\',valueinfo =\'产品搜索\',tips=\'产品搜索功能，按标题、参数、内容模糊搜索\'',
  85 => 'pos =\'1\',no_order=\'22\',type=\'4\',style=\'3\',selectd=\'$M$左$T$1$M$右$T$2$M$上$T$3$M$下$T$4$M$居中$T$5\',name =\'banner2_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'文字区域位置\',tips=\'\'',
  86 => 'pos =\'3\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表文章数量\',tips=\'\'',
  87 => 'pos =\'0\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_tel\',value=\'\',defaultvalue=\'\',valueinfo =\'服务热线\',tips=\'\'',
  88 => 'pos =\'2\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_placeholder\',value=\'Search\',defaultvalue=\'Search\',valueinfo =\'搜索框文字\',tips=\'\'',
  89 => 'pos =\'3\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_allcolumn\',value=\'所有案例\',defaultvalue=\'所有案例\',valueinfo =\'侧栏栏目区块标题\',tips=\'\'',
  90 => 'pos =\'1\',no_order=\'23\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'新闻区块一\',tips=\'\'',
  91 => 'pos =\'0\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_dsc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字\',tips=\'\'',
  92 => 'pos =\'3\',no_order=\'24\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\'',
  93 => 'pos =\'2\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'pro_column_xlg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器宽度大于1600像素\'',
  94 => 'pos =\'1\',no_order=\'24\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'home_news_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示\',tips=\'\'',
  95 => 'pos =\'0\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_info_wxok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'微信\',tips=\'\'',
  96 => 'pos =\'3\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'显示$T$1$M$隐藏$T$0$M$\',name =\'download_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\'',
  97 => 'pos =\'2\',no_order=\'25\',type=\'2\',style=\'3\',selectd=\'\',name =\'pro_column_md\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器宽度大于992像素小于1600像素\'',
  98 => 'pos =\'1\',no_order=\'25\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'标题\',tips=\'\'',
  99 => 'pos =\'0\',no_order=\'26\',type=\'7\',style=\'3\',selectd=\'\',name =\'foot_info_wx\',value=\'\',defaultvalue=\'\',valueinfo =\'微信二维码\',tips=\'\'',
  100 => 'pos =\'3\',no_order=\'26\',type=\'6\',style=\'3\',selectd=\'\',name =\'download_bar_list_id\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏文章列表调用栏目\',tips=\'默认调用当前栏目的内容\'',
  101 => 'pos =\'2\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'pro_column_sm\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于768像素小于992像素\'',
  102 => 'pos =\'1\',no_order=\'26\',type=\'3\',style=\'3\',selectd=\'\',name =\'home_news_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'描述\',tips=\'\'',
  103 => 'pos =\'0\',no_order=\'27\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_info_qqok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ\',tips=\'\'',
  104 => 'pos =\'3\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\'',
  105 => 'pos =\'2\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'pro_column_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\'',
  106 => 'pos =\'1\',no_order=\'27\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_news_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用栏目\',tips=\'调用指定栏目图文内容列表\'',
  107 => 'pos =\'0\',no_order=\'28\',type=\'4\',style=\'3\',selectd=\'个人QQ$T$1$M$企业营销QQ$T$2$M$\',name =\'foot_info_qqtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ类型\',tips=\'个人QQ和企业营销QQ超链接结构不一样，因此请务必选择正确。\'',
  108 => 'pos =\'2\',no_order=\'28\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\'',
  109 => 'pos =\'3\',no_order=\'28\',type=\'4\',style=\'3\',selectd=\'$M$全部文章$T$$M$推荐文章$T$com\',name =\'download_bar_list_type\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏列表文章类型\',tips=\'文章调用类型，【推荐文章】可以在添加或管理文章时设置。\'',
  110 => 'pos =\'1\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'\'',
  111 => 'pos =\'0\',no_order=\'29\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_qq\',value=\'\',defaultvalue=\'\',valueinfo =\'QQ号码\',tips=\'点击QQ链接可直接对话，需要先到 shang.qq.com 免费开通。<br/>企业营销QQ 无需开通\'',
  112 => 'pos =\'3\',no_order=\'29\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表文章数量\',tips=\'\'',
  113 => 'pos =\'2\',no_order=\'29\',type=\'4\',style=\'3\',selectd=\'$M$全屏列表$T$0$M$居中列表$T$1\',name =\'img_listtype\',value=\'0\',defaultvalue=\'0\',valueinfo =\'列表模式\',tips=\'\'',
  114 => 'pos =\'1\',no_order=\'29\',type=\'4\',style=\'3\',selectd=\'$M$全部文章$T$$M$推荐文章$T$com\',name =\'home_news_type\',value=\'\',defaultvalue=\'\',valueinfo =\'调用类型\',tips=\'文章调用类型，【推荐文章】可以在添加或管理文章时设置。\'',
  115 => 'pos =\'0\',no_order=\'30\',type=\'4\',style=\'3\',selectd=\'显示$T$1$M$隐藏$T$0$M$\',name =\'foot_info_sinaok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'新浪微博\',tips=\'\'',
  116 => 'pos =\'3\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_allcolumn\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'侧栏栏目区块标题\',tips=\'\'',
  117 => 'pos =\'2\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_listlook\',value=\'浏览\',defaultvalue=\'浏览\',valueinfo =\'按钮文字\',tips=\'\'',
  118 => 'pos =\'1\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_des_max\',value=\'50\',defaultvalue=\'50\',valueinfo =\'描述文字字数\',tips=\'描述文字最多显示字数（最大设置值200）\'',
  119 => 'pos =\'1\',no_order=\'31\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'新闻区块二\',tips=\'\'',
  120 => 'pos =\'0\',no_order=\'31\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_sina\',value=\'\',defaultvalue=\'\',valueinfo =\'新浪微博网址\',tips=\'请输入微博网址\'',
  121 => 'pos =\'3\',no_order=\'31\',type=\'1\',style=\'3\',selectd=\'\',name =\'页面文字\',value=\'\',defaultvalue=\'\',valueinfo =\'页面文字\',tips=\'\'',
  122 => 'pos =\'2\',no_order=\'31\',type=\'4\',style=\'3\',selectd=\'$M$浏览模式$T$1$M$详情模式$T$0\',name =\'img_listlook_style\',value=\'1\',defaultvalue=\'1\',valueinfo =\'查看模式\',tips=\'浏览模式为在列表页浏览图片，详情模式为点击进入详情页；【系统模式】下有效！\'',
  123 => 'pos =\'1\',no_order=\'32\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'home_service_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示\',tips=\'\'',
  124 => 'pos =\'0\',no_order=\'32\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_info_twitterok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'twitter（推特）\',tips=\'\'',
  125 => 'pos =\'3\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'preinfo\',value=\'上一篇\',defaultvalue=\'上一篇\',valueinfo =\'上一篇文字\',tips=\'\'',
  126 => 'pos =\'2\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_column_xlg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器宽度大于1600像素\'',
  127 => 'pos =\'1\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_title1\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'01标题\',tips=\'\'',
  128 => 'pos =\'0\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_twitter\',value=\'\',defaultvalue=\'\',valueinfo =\'twitter网址\',tips=\'\'',
  129 => 'pos =\'3\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'nextinfo\',value=\'下一篇\',defaultvalue=\'下一篇\',valueinfo =\'下一篇文字\',tips=\'\'',
  130 => 'pos =\'2\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_column_md\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器宽度大于992像素小于1600像素\'',
  131 => 'pos =\'1\',no_order=\'34\',type=\'3\',style=\'3\',selectd=\'\',name =\'home_allnews_desc1\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'01描述\',tips=\'\'',
  132 => 'pos =\'0\',no_order=\'34\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_info_googleok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'google+\',tips=\'\'',
  133 => 'pos =\'2\',no_order=\'34\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_column_sm\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于768像素小于992像素\'',
  134 => 'pos =\'3\',no_order=\'34\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'侧栏栏目\',tips=\'\'',
  135 => 'pos =\'1\',no_order=\'35\',type=\'6\',style=\'4\',selectd=\'\',name =\'home_allnews_id1\',value=\'\',defaultvalue=\'\',valueinfo =\'01调用栏目\',tips=\'调用指定栏目列表，如果指定栏目为文章模块则显示内容列表图片，标题和描述，如果指定栏目为图片模块和产品模块则显示内容列表图片，标题\'',
  136 => 'pos =\'0\',no_order=\'35\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_google\',value=\'\',defaultvalue=\'\',valueinfo =\'google+网址\',tips=\'\'',
  137 => 'pos =\'2\',no_order=\'35\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_column_xs\',value=\'1\',defaultvalue=\'1\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\'',
  138 => 'pos =\'3\',no_order=\'35\',type=\'2\',style=\'3\',selectd=\'\',name =\'bar_placeholder\',value=\'Search\',defaultvalue=\'Search\',valueinfo =\'搜索框文字\',tips=\'\'',
  139 => 'pos =\'0\',no_order=\'36\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_info_facebookok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'Facebook\',tips=\'\'',
  140 => 'pos =\'3\',no_order=\'36\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'bar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'除开产品模块以外的侧栏\'',
  141 => 'pos =\'2\',no_order=\'36\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'showleft_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'左边区域开关\',tips=\'此区域调用所在栏目的关键词和描述\'',
  142 => 'pos =\'1\',no_order=\'36\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_w1\',value=\'240\',defaultvalue=\'240\',valueinfo =\'01缩略图宽\',tips=\'\'',
  143 => 'pos =\'0\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_facebook\',value=\'\',defaultvalue=\'\',valueinfo =\'Facebook网址\',tips=\'\'',
  144 => 'pos =\'2\',no_order=\'37\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'招聘模块\',tips=\'\'',
  145 => 'pos =\'3\',no_order=\'37\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'bar_column3_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'除开产品模块以外的侧栏\'',
  146 => 'pos =\'1\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_h1\',value=\'240\',defaultvalue=\'240\',valueinfo =\'01缩略图高\',tips=\'\'',
  147 => 'pos =\'0\',no_order=\'38\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'foot_info_emailok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'邮箱\',tips=\'\'',
  148 => 'pos =\'2\',no_order=\'38\',type=\'2\',style=\'3\',selectd=\'\',name =\'cvtitle\',value=\'在线应聘\',defaultvalue=\'在线应聘\',valueinfo =\'按钮文字\',tips=\'\'',
  149 => 'pos =\'3\',no_order=\'38\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'分享代码\',tips=\'\'',
  150 => 'pos =\'1\',no_order=\'38\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_title2\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'02标题\',tips=\'\'',
  151 => 'pos =\'0\',no_order=\'39\',type=\'2\',style=\'3\',selectd=\'\',name =\'foot_info_email\',value=\'\',defaultvalue=\'\',valueinfo =\'邮箱地址\',tips=\'访客点击可以直接发送邮件\'',
  152 => 'pos =\'2\',no_order=\'39\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\'',
  153 => 'pos =\'3\',no_order=\'39\',type=\'3\',style=\'3\',selectd=\'\',name =\'sharecode\',value=\'\',defaultvalue=\'\',valueinfo =\'代码\',tips=\'请将获取到的分享按钮代码粘贴到输入框，需要注意的是，添加分享代码会让页面加载变慢。\'',
  154 => 'pos =\'1\',no_order=\'39\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_desc2\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'02描述\',tips=\'\'',
  155 => 'pos =\'0\',no_order=\'40\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'页面文字\',tips=\'\'',
  156 => 'pos =\'2\',no_order=\'40\',type=\'2\',style=\'3\',selectd=\'\',name =\'download\',value=\'立即下载\',defaultvalue=\'立即下载\',valueinfo =\'按钮文字\',tips=\'详情页按钮也是此处文字\'',
  157 => 'pos =\'1\',no_order=\'40\',type=\'6\',style=\'4\',selectd=\'\',name =\'home_allnews_id2\',value=\'\',defaultvalue=\'\',valueinfo =\'02调用栏目\',tips=\'调用指定栏目列表，如果指定栏目为文章模块则显示内容列表图片，标题和描述，如果指定栏目为图片模块和产品模块则显示内容列表图片，标题\'',
  158 => 'pos =\'0\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'页面文字\',tips=\'\'',
  159 => 'pos =\'2\',no_order=\'41\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'简介模块\',tips=\'\'',
  160 => 'pos =\'1\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_w2\',value=\'240\',defaultvalue=\'240\',valueinfo =\'02缩略图宽\',tips=\'\'',
  161 => 'pos =\'0\',no_order=\'42\',type=\'2\',style=\'3\',selectd=\'\',name =\'ajaxpagemore\',value=\'加载更多\',defaultvalue=\'加载更多\',valueinfo =\'分页文字\',tips=\'无刷新分页默认文字\'',
  162 => 'pos =\'2\',no_order=\'42\',type=\'4\',style=\'3\',selectd=\'$M$默认样式$T$0$M$个性化样式$T$1\',name =\'showstyle1\',value=\'1\',defaultvalue=\'1\',valueinfo =\'页面样式\',tips=\'默认样式展示的是该栏目的内容，个性化样式展示(选择个性化样式+栏目标识为5的简介模块)的是该栏目的标题及内容，如果该栏目有二级栏目则展示该栏目的标题及内容+二级栏目（如果图片模块。调用的是指定栏目的推荐内容，选择其他模块的，则调用 指定栏目的二级栏目下的三级栏目标题及描述）\'',
  163 => 'pos =\'1\',no_order=\'42\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_h2\',value=\'240\',defaultvalue=\'240\',valueinfo =\'02缩略图高\',tips=\'\'',
  164 => 'pos =\'0\',no_order=\'43\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'系统设置\',tips=\'\'',
  165 => 'pos =\'1\',no_order=\'43\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_title3\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'03标题\',tips=\'\'',
  166 => 'pos =\'2\',no_order=\'43\',type=\'4\',style=\'3\',selectd=\'$M$纯展示$T$0$M$超链接$T$1\',name =\'showlink\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示方式\',tips=\'针对于该栏目下的三级栏目\'',
  167 => 'pos =\'0\',no_order=\'44\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'lazyloadbg_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'背景图开关\',tips=\'关闭背景图则图片加载过程中采用默认的灰色背景，IE/safari浏览器不支持此设置，只显示灰色背景\'',
  168 => 'pos =\'1\',no_order=\'44\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_desc3\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'03描述\',tips=\'\'',
  169 => 'pos =\'0\',no_order=\'45\',type=\'7\',style=\'3\',selectd=\'\',name =\'lazyloadbg\',value=\'\',defaultvalue=\'\',valueinfo =\'图片加载背景图\',tips=\'图片延迟加载过程中的背景图，建议上传宽高都小于50像素的背景透明的图片，默认采用圆环图\'',
  170 => 'pos =\'1\',no_order=\'45\',type=\'6\',style=\'4\',selectd=\'\',name =\'home_allnews_id3\',value=\'\',defaultvalue=\'\',valueinfo =\'03调用栏目\',tips=\'调用指定栏目列表，如果指定栏目为文章模块则显示内容列表图片，标题和描述，如果指定栏目为图片模块和产品模块则显示内容列表图片，标题\'',
  171 => 'pos =\'1\',no_order=\'46\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_w3\',value=\'240\',defaultvalue=\'240\',valueinfo =\'03缩略图宽\',tips=\'\'',
  172 => 'pos =\'1\',no_order=\'47\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_h3\',value=\'240\',defaultvalue=\'240\',valueinfo =\'03缩略图高\',tips=\'\'',
  173 => 'pos =\'1\',no_order=\'48\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_title4\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'04标题\',tips=\'\'',
  174 => 'pos =\'1\',no_order=\'49\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_allnews_desc4\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'04描述\',tips=\'\'',
  175 => 'pos =\'1\',no_order=\'50\',type=\'6\',style=\'4\',selectd=\'\',name =\'home_allnews_id4\',value=\'\',defaultvalue=\'\',valueinfo =\'04调用栏目\',tips=\'调用指定栏目列表，如果指定栏目为文章模块则显示内容列表图片，标题和描述，如果指定栏目为图片模块和产品模块则显示内容列表图片，标题\'',
  176 => 'pos =\'1\',no_order=\'51\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_h4\',value=\'240\',defaultvalue=\'240\',valueinfo =\'04缩略图高\',tips=\'\'',
  177 => 'pos =\'1\',no_order=\'52\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_w4\',value=\'240\',defaultvalue=\'240\',valueinfo =\'04缩略图宽\',tips=\'\'',
  178 => 'pos =\'1\',no_order=\'53\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$$M$推荐$T$com\',name =\'home_newsll_type\',value=\'\',defaultvalue=\'\',valueinfo =\'调用类型\',tips=\'\'',
  179 => 'pos =\'1\',no_order=\'54\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'newsll_img_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示图片\',tips=\'\'',
  180 => 'pos =\'1\',no_order=\'55\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_newsll_num\',value=\'4\',defaultvalue=\'4\',valueinfo =\'文章模块调用条数\',tips=\'\'',
  181 => 'pos =\'1\',no_order=\'56\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_imgsll_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'图片模块调用条数\',tips=\'\'',
  182 => 'pos =\'1\',no_order=\'57\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_newsall_des_max\',value=\'50\',defaultvalue=\'50\',valueinfo =\'描述字数\',tips=\'\'',
  183 => 'pos =\'1\',no_order=\'58\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'专题列表区\',tips=\'\'',
  184 => 'pos =\'1\',no_order=\'59\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'home_product_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示\',tips=\'图片尺寸设置为所选栏目对应模块的缩略图尺寸\'',
  185 => 'pos =\'1\',no_order=\'60\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'标题\',tips=\'\'',
  186 => 'pos =\'1\',no_order=\'61\',type=\'3\',style=\'3\',selectd=\'\',name =\'home_product_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'描述\',tips=\'\'',
  187 => 'pos =\'1\',no_order=\'62\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'home_topic_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示右上角的内容\',tips=\'\'',
  188 => 'pos =\'1\',no_order=\'63\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_topic_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'此栏目选择为右上角的内容,调用指定栏目的二级栏目的标题\'',
  189 => 'pos =\'1\',no_order=\'64\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_procolumn_xlg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器宽度大于1600像素\'',
  190 => 'pos =\'1\',no_order=\'65\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_procolumn_md\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器宽度大于992像素小于1600像素\'',
  191 => 'pos =\'1\',no_order=\'66\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_procolumn_sm\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于768像素小于992像素\'',
  192 => 'pos =\'1\',no_order=\'67\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_procolumn_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\'',
  193 => 'pos =\'1\',no_order=\'68\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_1\',value=\'\',defaultvalue=\'\',valueinfo =\'专题1名称\',tips=\'\'',
  194 => 'pos =\'1\',no_order=\'69\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_1_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题1链接\',tips=\'请填写完整链接\'',
  195 => 'pos =\'1\',no_order=\'70\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_1_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题1图片\',tips=\'\'',
  196 => 'pos =\'1\',no_order=\'71\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_2\',value=\'\',defaultvalue=\'\',valueinfo =\'专题2名称\',tips=\'\'',
  197 => 'pos =\'1\',no_order=\'72\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_2_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题2链接\',tips=\'请填写完整链接\'',
  198 => 'pos =\'1\',no_order=\'73\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_2_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题2图片\',tips=\'\'',
  199 => 'pos =\'1\',no_order=\'74\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_3\',value=\'\',defaultvalue=\'\',valueinfo =\'专题3名称\',tips=\'\'',
  200 => 'pos =\'1\',no_order=\'75\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_3_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题3链接\',tips=\'请填写完整链接\'',
  201 => 'pos =\'1\',no_order=\'76\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_3_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题3图片\',tips=\'\'',
  202 => 'pos =\'1\',no_order=\'77\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_4\',value=\'\',defaultvalue=\'\',valueinfo =\'专题4名称\',tips=\'\'',
  203 => 'pos =\'1\',no_order=\'78\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_4_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题4链接\',tips=\'请填写完整链接\'',
  204 => 'pos =\'1\',no_order=\'79\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_4_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题4图片\',tips=\'\'',
  205 => 'pos =\'1\',no_order=\'80\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_5\',value=\'\',defaultvalue=\'\',valueinfo =\'专题5名称\',tips=\'\'',
  206 => 'pos =\'1\',no_order=\'81\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_5_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题5链接\',tips=\'请填写完整链接\'',
  207 => 'pos =\'1\',no_order=\'82\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_5_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题5图片\',tips=\'\'',
  208 => 'pos =\'1\',no_order=\'83\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_6\',value=\'\',defaultvalue=\'\',valueinfo =\'专题6名称\',tips=\'\'',
  209 => 'pos =\'1\',no_order=\'84\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_6_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题6链接\',tips=\'请填写完整链接\'',
  210 => 'pos =\'1\',no_order=\'85\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_6_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题6图片\',tips=\'\'',
  211 => 'pos =\'1\',no_order=\'86\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_7\',value=\'\',defaultvalue=\'\',valueinfo =\'专题7名称\',tips=\'\'',
  212 => 'pos =\'1\',no_order=\'87\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_7_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题7链接\',tips=\'请填写完整链接\'',
  213 => 'pos =\'1\',no_order=\'88\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_7_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题7图片\',tips=\'\'',
  214 => 'pos =\'1\',no_order=\'89\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_8\',value=\'\',defaultvalue=\'\',valueinfo =\'专题8名称\',tips=\'\'',
  215 => 'pos =\'1\',no_order=\'90\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_info_8_url\',value=\'\',defaultvalue=\'\',valueinfo =\'专题8链接\',tips=\'请填写完整链接\'',
  216 => 'pos =\'1\',no_order=\'91\',type=\'7\',style=\'3\',selectd=\'\',name =\'topic_info_8_img\',value=\'\',defaultvalue=\'\',valueinfo =\'专题8图片\',tips=\'\'',
  217 => 'pos =\'1\',no_order=\'92\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_img_x\',value=\'\',defaultvalue=\'\',valueinfo =\'缩略图宽\',tips=\'\'',
  218 => 'pos =\'1\',no_order=\'93\',type=\'2\',style=\'3\',selectd=\'\',name =\'topic_img_y\',value=\'\',defaultvalue=\'\',valueinfo =\'缩略图高\',tips=\'\'',
  219 => 'pos =\'1\',no_order=\'94\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'关注我们\',tips=\'\'',
  220 => 'pos =\'1\',no_order=\'95\',type=\'4\',style=\'3\',selectd=\'$M$显示$T$1$M$隐藏$T$0\',name =\'home_about_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否显示\',tips=\'\'',
  221 => 'pos =\'1\',no_order=\'96\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_title\',value=\'\',defaultvalue=\'\',valueinfo =\'标题\',tips=\'\'',
  222 => 'pos =\'1\',no_order=\'97\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_desc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述\',tips=\'\'',
  223 => 'pos =\'1\',no_order=\'98\',type=\'8\',style=\'3\',selectd=\'\',name =\'home_about_content\',value=\'\',defaultvalue=\'\',valueinfo =\'内容\',tips=\'\'',
  224 => 'pos =\'1\',no_order=\'99\',type=\'1\',style=\'3\',selectd=\'\',name =\'\',value=\'\',defaultvalue=\'\',valueinfo =\'按钮文字\',tips=\'\'',
  225 => 'pos =\'1\',no_order=\'100\',type=\'2\',style=\'3\',selectd=\'\',name =\'more\',value=\'MORE >\',defaultvalue=\'MORE >\',valueinfo =\'链接按钮\',tips=\'\'',
);
$no='res025';
$devices='0';
		$re['sql'] = $sql;
		$re['no'] = $no;
		$re['devices'] = $devices;
		return $re;
	}
}

# This program is an open source system, commercial use, please consciously to purchase commercial license.
# Copyright (C) MetInfo Co., Ltd. (http://www.metinfo.cn). All rights reserved.
?>